# Generated by Django 4.2.30 on 2026-06-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='OutbreakAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(blank=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('diagnosis', models.CharField(max_length=300)),
                ('message', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('case_count', models.PositiveIntegerField(default=0)),
                ('facility_count', models.PositiveIntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('last_detected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_facilities', models.ManyToManyField(blank=True, related_name='outbreak_alerts', to='core.facility')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
