# Generated by Django 4.2.30 on 2026-06-05 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_profile_firebase_token_outbreakalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('identifier', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('in_transit', 'In transit'), ('charging', 'Charging'), ('maintenance', 'Maintenance')], default='ready', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drones', to='core.facility')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('reception', 'Reception'), ('nurse', 'Nurse / Triage'), ('doctor', 'Doctor'), ('lab', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('billing', 'Billing'), ('supervisor', 'Drug Supervisor'), ('supplier', 'Drug Supplier'), ('blood_bank', 'Blood Bank'), ('admin', 'System Admin')], default='patient', max_length=20),
        ),
        migrations.CreateModel(
            name='DroneDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('drug', 'Drug shipment'), ('blood', 'Blood delivery'), ('vaccine', 'Vaccines'), ('supplies', 'Medical supplies')], default='drug', max_length=20)),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='units', max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('destination_address', models.TextField(blank=True)),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('expected_arrival', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('current_status_notes', models.TextField(blank=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_transit', 'In transit'), ('delayed', 'Delayed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drone_destination_deliveries', to='core.facility')),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='core.drone')),
                ('origin_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drone_origin_deliveries', to='core.facility')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_drone_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugShortageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_until_runout', models.PositiveIntegerField()),
                ('estimated_daily_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('last_predicted_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('drug_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortage_alerts', to='core.drugstock')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortage_alerts', to='core.facility')),
            ],
            options={
                'ordering': ['-predicted_at'],
                'unique_together': {('facility', 'drug_stock')},
            },
        ),
    ]
